#!/usr/bin/env python3
"""Power analysis for Project A: How many seeds do you need?

Takes paired summary JSONs from project_a_pairwise_summary.py and simulates
what conclusion you'd reach with fewer seeds via bootstrap subsampling.

For each cell, computes:
- Probability of reaching the "correct" conclusion at N = 3, 5, 7, 10, 15, 20
- The "correct" conclusion is defined by the full-sample adjudication

Outputs a power analysis table and stability curves.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Power analysis for PEFT claim audit")
    p.add_argument(
        "--summary-jsons",
        nargs="+",
        required=True,
        help="Paired summary JSON files from project_a_pairwise_summary.py",
    )
    p.add_argument("--n-values", nargs="+", type=int, default=[3, 5, 7, 10, 15, 20])
    p.add_argument("--n-simulations", type=int, default=2000)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--out-json", default=None)
    p.add_argument("--out-md", default=None)
    return p.parse_args()


def sign_flip_pvalue(deltas: list[float]) -> float:
    """Compute sign-flip permutation p-value."""
    n = len(deltas)
    if n == 0:
        return 1.0
    observed = abs(sum(deltas))
    count = 0
    total = 2**n
    if total > 100000:
        # Monte Carlo approximation
        rng = random.Random(123)
        mc_n = 100000
        for _ in range(mc_n):
            flipped = sum(d * rng.choice([-1, 1]) for d in deltas)
            if abs(flipped) >= observed:
                count += 1
        return count / mc_n
    for mask in range(total):
        flipped = sum(d * (1 if (mask >> i) & 1 else -1) for i, d in enumerate(deltas))
        if abs(flipped) >= observed:
            count += 1
    return count / total


def bootstrap_ci(deltas: list[float], n_boot: int = 2000, seed: int = 42) -> tuple[float, float]:
    """Percentile bootstrap CI."""
    rng = random.Random(seed)
    n = len(deltas)
    means = []
    for _ in range(n_boot):
        sample = [deltas[rng.randint(0, n - 1)] for _ in range(n)]
        means.append(sum(sample) / len(sample))
    means.sort()
    lo = means[int(0.025 * len(means))]
    hi = means[int(0.975 * len(means))]
    return lo, hi


def adjudicate(mean_delta: float, ci_low: float, ci_high: float, p_value: float) -> str:
    """Adjudicate a claim cell."""
    if mean_delta > 0 and ci_low > 0:
        return "supported"
    elif mean_delta < 0 and ci_high < 0:
        return "reversed"
    else:
        return "unsupported"


def simulate_subsampling(
    per_seed: list[dict], n_values: list[int], n_sim: int, rng_seed: int
) -> dict[int, dict]:
    """For each N, subsample N seeds and compute adjudication."""
    rng = random.Random(rng_seed)
    all_deltas = [s["delta"] for s in per_seed]
    full_mean = sum(all_deltas) / len(all_deltas)
    full_ci = bootstrap_ci(all_deltas)
    full_p = sign_flip_pvalue(all_deltas)
    full_adj = adjudicate(full_mean, full_ci[0], full_ci[1], full_p)

    results = {}
    for n in n_values:
        if n > len(per_seed):
            results[n] = {
                "n": n,
                "match_rate": float("nan"),
                "supported_rate": float("nan"),
                "unsupported_rate": float("nan"),
                "reversed_rate": float("nan"),
                "note": f"N={n} > available seeds ({len(per_seed)})",
            }
            continue

        match_count = 0
        adj_counts = {"supported": 0, "unsupported": 0, "reversed": 0}

        for _ in range(n_sim):
            subset = rng.sample(per_seed, n)
            deltas = [s["delta"] for s in subset]
            mean_d = sum(deltas) / len(deltas)
            ci = bootstrap_ci(deltas, n_boot=500, seed=rng.randint(0, 99999))
            p = sign_flip_pvalue(deltas)
            adj = adjudicate(mean_d, ci[0], ci[1], p)
            adj_counts[adj] += 1
            if adj == full_adj:
                match_count += 1

        results[n] = {
            "n": n,
            "match_rate": round(match_count / n_sim, 4),
            "supported_rate": round(adj_counts["supported"] / n_sim, 4),
            "unsupported_rate": round(adj_counts["unsupported"] / n_sim, 4),
            "reversed_rate": round(adj_counts["reversed"] / n_sim, 4),
        }

    return {"full_adjudication": full_adj, "full_mean_delta": full_mean,
            "full_p": full_p, "full_n": len(per_seed), "subsampling": results}


def generate_markdown(all_results: list[dict], n_values: list[int]) -> str:
    lines = [
        "# Power Analysis: How Many Seeds Do You Need?",
        "",
        "Generated by `power_analysis.py`",
        "",
        "## Summary Table",
        "",
    ]

    # Build header
    header = "| Cell | Full Adj. | Full Δ | Full p |"
    sep = "|------|-----------|--------|--------|"
    for n in n_values:
        header += f" N={n} |"
        sep += "------|"
    lines.append(header)
    lines.append(sep)

    for r in all_results:
        row = (
            f"| {r['cell_name']} | {r['full_adjudication']} "
            f"| {r['full_mean_delta']:+.4f} | {r['full_p']:.4f} |"
        )
        for n in n_values:
            if n in r["subsampling"]:
                match = r["subsampling"][n]["match_rate"]
                row += f" {match:.0%} |"
            else:
                row += " N/A |"
        lines.append(row)

    lines.append("")
    lines.append("*Values show probability of reaching the same conclusion as the full-sample adjudication.*")
    lines.append("")

    # Detailed per-cell
    for r in all_results:
        lines.append(f"## {r['cell_name']}")
        lines.append("")
        lines.append(f"- Full sample: N={r['full_n']}, Δ={r['full_mean_delta']:+.6f}, p={r['full_p']:.6f}, **{r['full_adjudication']}**")
        lines.append("")
        lines.append("| N | Match Rate | Supported % | Unsupported % | Reversed % |")
        lines.append("|---|-----------|------------|--------------|-----------|")
        for n in n_values:
            if n in r["subsampling"]:
                s = r["subsampling"][n]
                lines.append(
                    f"| {n} | {s['match_rate']:.1%} | {s['supported_rate']:.1%} "
                    f"| {s['unsupported_rate']:.1%} | {s['reversed_rate']:.1%} |"
                )
        lines.append("")

    # Key findings
    lines.append("## Key Findings")
    lines.append("")
    for r in all_results:
        # Find minimum N where match rate >= 80%
        min_n = None
        for n in n_values:
            if n in r["subsampling"] and r["subsampling"][n]["match_rate"] >= 0.80:
                min_n = n
                break
        if min_n:
            lines.append(f"- **{r['cell_name']}**: N≥{min_n} needed for ≥80% stability ({r['full_adjudication']})")
        else:
            lines.append(f"- **{r['cell_name']}**: Even N={max(n_values)} insufficient for 80% stability")

    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    all_results = []
    for json_path in args.summary_jsons:
        with open(json_path) as f:
            summary = json.load(f)

        cell_name = f"{summary['candidate_name']} vs {summary['baseline_name']}"
        # Infer task from filename
        fname = Path(json_path).stem
        if "mnli" in fname:
            cell_name += " / MNLI"
        elif "boolq" in fname:
            cell_name += " / BoolQ"
        elif "gsm8k" in fname:
            cell_name += " / GSM8K"
        elif "squad" in fname:
            cell_name += " / SQuAD"

        # Add seed count info
        n_seeds = len(summary["per_seed"])
        cell_name += f" ({n_seeds}s)"

        print(f"Analyzing: {cell_name}")
        result = simulate_subsampling(
            summary["per_seed"], args.n_values, args.n_simulations, args.seed
        )
        result["cell_name"] = cell_name
        all_results.append(result)

    if args.out_json:
        out = Path(args.out_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w") as f:
            json.dump(all_results, f, indent=2)
        print(f"JSON: {out}")

    md = generate_markdown(all_results, args.n_values)
    if args.out_md:
        out = Path(args.out_md)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w") as f:
            f.write(md)
        print(f"Markdown: {out}")
    else:
        print(md)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
